export const ErrorCodes = Object.freeze({
  //HTTP
  UN_AUTHORIZED: 'unauthorized',
  NOT_FOUND: 'not_found',
  BAD_REQUEST: 'bad_request',
  INTERNAL_SERVER_ERROR: 'internal_server_error',
  CONFLICT: 'conflict',
  ARGUMENT_OUT_OF_RANGE: 'argument_out_of_range',
  ARGUMENT_INVALID: 'argument_invalid',
  ARGUMENT_NOT_PROVIDED: 'argument_not_provided',
  PAYMENT_REQUIRED: 'payment_required',
  LIMIT_EXCEEDED: 'limit_exceeded',
  //COMMON
  INVALID_STATUS: 'invalid_status',
  ENTITY_IS_USING_BY_ANOTHER_ENTITY: 'entity_is_using_by_another_entity',
  RECEIVERS_IS_EMPTY: 'receivers_is_empty',
  INVALID_DATE: 'invalid_date',
  MODULE_SUBSCRIPTION_REQUIRED: 'module_subscription_required',
  MODULE_SUBSCRIPTION_CANT_SUSPEND: 'module_subscription_cant_suspend',
  MODULE_SUBSCRIPTION_SUSPEND_FREQUENCY_LIMIT_EXCEEDED:
    'module_subscription_suspend_frequency_limit_exceeded',
  MODULE_SUBSCRIPTION_CANT_CANCEL: 'module_subscription_cant_cancel',
  MODULE_SUBSCRIPTION_CANT_ACTIVATE: 'module_subscription_cant_activate',
  MODULE_SUBSCRIPTION_CANT_EXPIRE: 'module_subscription_cant_expire',
  MODULE_SUBSCRIPTION_IS_EXPIRED: 'module_subscription_is_expired',
  INVALID_MODULE: 'invalid_module',
  INVALID_PRICE_VALUE: 'invalid_price_value',
  MODULE_SUBSCRIPTION_INVOICE_CANT_UPDATE_AS_PAID:
    'module_subscription_invoice_cant_update_as_paid',
  MODULE_SUBSCRIPTION_INVOICE_CANT_UPDATE_AS_CANCELED:
    'module_subscription_invoice_cant_update_as_canceled',
  MODULE_SUBSCRIPTION_INVOICE_BILLING_END_DATE_REQUIRED:
    'module_subscription_invoice_billing_end_date_required',
  MODULE_SUBSCRIPTION_INVOICE_BILLING_START_DATE_REQUIRED:
    'module_subscription_invoice_billing_start_date_required',
  MODULE_SUBSCRIPTION_INVOICE_DUE_DATE_REQUIRED:
    'module_subscription_invoice_due_date_required',
  MODULE_SUBSCRIPTION_INVOICE_INVALID_AMOUNT:
    'module_subscription_invoice_invalid_amount',
  MODULE_SUBSCRIPTION_INVOICE_NOT_FOUND:
    'module_subscription_invoice_not_found',
  REVIEW_NOTE_REQUIRED: 'review_note_required',
  INVALID_REVIEW_STATUS: 'invalid_review_status',
  USE_CRM_MODULE_INSTEAD: 'use_crm_module_instead',
  NEGATIVITY_CAUSE_REQUIRED: 'negativity_cause_required',
  //ACCOUNT
  ACCOUNT_IS_NOT_ACTIVE: 'account_is_not_active',
  ACCOUNT_NOT_FOUND: 'account_not_found',
  ACCOUNT_ACTIVATION_TOKEN_EXPIRED: 'account_activation_token_expired',
  ACCOUNT_ACTIVATION_TOKEN_REQUIRED: 'account_activation_token_required',
  ACCOUNT_RESET_PASSWORD_TOKEN_REQUIRED:
    'account_reset_password_token_required',
  ACCOUNT_RESET_PASSWORD_TOKEN_EXPIRED: 'account_reset_password_token_expired',
  ACCOUNT_RESET_PASSWORD_OPERATION_BREACHED:
    'account_reset_password_operation_breached',
  USERS_CANT_DELETE_THEMSELVES: 'users_cant_delete_themselves',
  USERS_CANT_UPDATE_PERMISSIONS_THEMSELVES:
    'users_cant_update_permissions_themselves',
  ROLE_NOT_FOUND: 'role_not_found',
  PASSWORDS_DONT_MATCH: 'passwords_dont_match',
  ACCOUNT_ISSUE_NOT_FOUND: 'account_issue_not_found',

  //COMMON DEFINITION
  LOCALE_NOT_FOUND: 'locale_not_found',
  PRODUCT_NOT_FOUND: 'product_not_found',
  PRODUCT_ITEM_NOT_FOUND: 'product_item_not_found',
  UNIT_NOT_FOUND: 'unit_not_found',
  UNIT_NAME_NOT_FOUND: 'unit_name_not_found',
  UNIT_CANT_UPDATE: 'unit_can_not_update',
  TOPIC_NOT_FOUND: 'topic_not_found',
  TOPIC_NAME_NOT_FOUND: 'topic_name_not_found',
  TOPIC_TYPE_NOT_FOUND: 'topic_type_not_found',
  TOPIC_TYPE_REQUIRED: 'topic_type_required',
  PAGE_NOT_FOUND: 'page_not_found',
  PAGE_CONTENT_CANT_BE_EMPTY: 'page_content_cant_be_empty',
  EXERCISE_NOT_FOUND: 'exercise_not_found',
  EXERCISE_CONTENT_NOT_FOUND: 'exercise_content_not_found',
  EXERCISE_GROUP_NOT_FOUND: 'exercise_group_not_found',
  EXERCISE_GROUP_NAME_NOT_FOUND: 'exercise_group_name_not_found',
  INVALID_EXERCISE_TYPE: 'invalid_exercise_type',
  CALENDAR_ENTRY_NOT_FOUND: 'calendar_entry_not_found',
  CALENDAR_ENTRY_NAME_NOT_FOUND: 'calendar_entry_name_not_found',
  CALENDAR_ENTRY_DATE_NOT_FOUND: 'calendar_entry_date_not_found',
  CALENDAR_ENTRY_TIME_RANGE_NOT_FOUND: 'calendar_entry_time_range_not_found',
  EDUCATION_LEVEL_NOT_FOUND: 'education_level_not_found',
  EDUCATION_THEME_NOT_FOUND: 'education_theme_not_found',
  EDUCATION_TYPE_NOT_FOUND: 'education_type_not_found',
  EDUCATION_FIELD_NOT_FOUND: 'education_field_not_found',
  CONTENT_VERSION_NOT_FOUND: 'content_version_not_found',
  CONTENT_VERSION_CANT_UPDATE: 'content_version_can_not_update',
  CONTENT_VERSION_CANT_DELETE: 'content_version_can_not_delete',
  CONTENT_VERSION_CANT_ARCHIVE: 'content_version_can_not_delete',
  CONTENT_VERSION_REVIEWED_BEFORE_PUBLISH:
    'content_version_should_be_reviewed_before_publish',
  CONTENT_VERSION_PUBLISHED_BEFORE_SET_AS_DEFAULT:
    'content_version_should_be_published_before_set_as_default',
  CONTENT_VERSION_UPDATE_PACKAGE_NOT_FOUND:
    'content_version_update_package_not_found',
  CONTENT_VERSION_NAME_NOT_FOUND: 'content_version_name_not_found',
  COUNTRY_CODE_NOT_FOUND: 'country_code_not_found',
  COUNTRY_NAME_NOT_FOUND: 'country_name_not_found',
  CITY_CODE_NOT_FOUND: 'city_code_not_found',
  CITY_NAME_NOT_FOUND: 'city_name_not_found',
  ADDRESS_NOT_FOUND: 'address_not_found',
  POSTAL_CODE_NOT_FOUND: 'postal_code_not_found',
  PHONE_NUMBER_NOT_FOUND: 'phone_number_not_found',
  BEGIN_TIME_NOT_FOUND: 'begin_time_not_found',
  END_TIME_NOT_FOUND: 'end_time_not_found',
  END_TIME_SHOULD_BE_AFTER_BEGIN_TIME: 'end_time_should_be_after_begin_time',
  HOUR_IS_OUT_OF_RANGE: 'hour_is_out_of_range',
  MINUTE_IS_OUT_OF_RANGE: 'minute_is_out_of_range',
  START_DATE_NOT_FOUND: 'start_date_not_found',
  START_DATE_AND_END_DATE_NOT_FOUND: 'start_date_and_end_date_not_found',
  END_DATE_NOT_FOUND: 'end_date_not_found',
  START_DATE_SHOULD_BE_BEFORE_END_DATE: 'start_date_should_be_before_end_date',
  OWNER_NOT_FOUND: 'owner_not_found',
  EMAIL_RECEIVER_NOT_FOUND: 'email_receiver_not_found',
  EMAIL_NOT_FOUND: 'email_not_found',
  INVALID_TEACHER_SCORE: 'invalid_teacher_score',
  INVALID_EXAM_SCORE: 'invalid_exam_score',
  INVALID_HOMEWORK_SCORE: 'invalid_homework_score',
  INVALID_ATTENDANCE_SCORE: 'invalid_attendance_score',
  INVALID_ATTENDANCE_SCORE_THRESHOLD: 'invalid_attendance_score_threshold',
  INVALID_FAIL_SCORE_THRESHOLD: 'invalid_fail_score_threshold',
  INVALID_SUCCESS_SCORE_THRESHOLD: 'invalid_success_score_threshold',
  EDUCATION_LEVEL_SUCCESS_REQUIREMENT_NOT_FOUND:
    'education_level_success_requirement_not_found',
  HOME_WORK_NOT_FOUND: 'homework_not_found',
  HOME_WORK_DUE_DATE_IS_EXPIRED: 'homework_due_date_is_expired',
  HOME_WORK_ALREADY_EXISTS: 'homework_already_exists',
});
